version: '2'

services:
  emacs28.0.90:
    image: harbor.homew.keenetic.pro/eab/emacs28.0.90:0.0.1
    container_name: emacs28.0.90
    hostname: emacs28.0.90
    privileged: true
    network_mode: bridge
    volumes:
      - /home/eab/data/gitno/github/eab-docker-emacs/:/mnt/workspace
      - /home/eab/.ssh:/home/eab/.ssh
      - /home/eab/git/:/home/eab/git/
      - /home/eab/.bashrc:/home/eab/.bashrc
      - /home/eab/.profile:/home/eab/.profile
      - /etc/ssh:/etc/ssh
      - /tmp/user:/tmp/user
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - 'UNAME=eab'
      - 'GNAME=eab'
      - 'UID=1000'
      - 'GID=1000'
      - 'UHOME=/home/eab'
      - 'LANG=ru_RU.UTF-8'
      - 'LC_ALL=en_US.UTF-8'
      - 'TZ=Asia/Vladivostok'
      - 'DISPLAY=$DISPLAY'
      - 'TERM=xterm-256color'
    devices:
      - "/dev/console:/dev/console:rw"
