ARG VERSION=20.04
FROM ubuntu:$VERSION

MAINTAINER eab <artscan@list.ru>

RUN echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf \
    && apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install \
    software-properties-common \
    libxpm-dev \
    libgif-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libx11-dev \
    libncurses5-dev \
    automake \
    autoconf \
    texinfo \
    libgtk2.0-dev \
    && add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt-get install \
    gcc-10 \
    g++-10 \
    libgccjit0 \
    libgccjit-10-dev \
    libjansson4 \
    libjansson-dev \
    libxml2-dev \
    supervisor \
    openssh-server \
    libgnutls28-dev

# basic stuff
RUN echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf \
    && apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install \
    bash \
    build-essential \
    dbus-x11 \
    fontconfig \
    git \
    gzip \
    language-pack-en-base \
    libgl1-mesa-glx \
    make \
    sudo \
    tar \
    unzip \
    expect \
    tmux \
    python \
    python-dev \
    python3-pip \
    openvpn \
    curl \
    man \
    strace \
    lsof \
    wget \
# su-exec
    && git clone https://github.com/ncopa/su-exec.git /tmp/su-exec \
    && cd /tmp/su-exec \
    && make \
    && chmod 770 su-exec \
    && mv ./su-exec /usr/local/sbin/ \
# git-wip
    && git clone git://github.com/bartman/git-wip.git && cp git-wip/git-wip /usr/bin \
# ripgrep
    && wget https://github.com/BurntSushi/ripgrep/releases/download/12.0.1/ripgrep-12.0.1-x86_64-unknown-linux-musl.tar.gz \
    && tar -xvf ripgrep-12.0.1-x86_64-unknown-linux-musl.tar.gz && cp ripgrep-12.0.1-x86_64-unknown-linux-musl/rg /usr/bin \
# Cleanup
    && apt-get purge build-essential \
    && apt-get autoremove \
    && rm -rf /tmp/* /var/lib/apt/lists/* /root/.cache/*

COPY emacs-28.0.90 /emacs
COPY build.sh /emacs/build.sh
RUN cd /emacs && chmod +x build.sh && sleep 1 && ./build.sh
RUN rm -rf /emacs

RUN mkdir /var/run/sshd

COPY dockerfiles/asEnvUser /usr/local/sbin/

# Only for sudoers
RUN chown root /usr/local/sbin/asEnvUser \
    && chmod 700  /usr/local/sbin/asEnvUser


# Supervisor Config
COPY ./config/supervisor/supervisord.conf /etc/supervisord.conf
# Start Supervisord
COPY ./config/cmd.sh /
RUN chmod 755 /cmd.sh

ENV UNAME="emacser" \
    GNAME="emacs" \
    UHOME="/home/emacs" \
    UID="1000" \
    GID="1000" \
    WORKSPACE="/mnt/workspace" \
    SHELL="/bin/bash"

WORKDIR "${WORKSPACE}"

ENTRYPOINT ["asEnvUser"]
CMD ["bash", "-c", "/cmd.sh"]
