name: Greeting from Github

on:
  push:
    branches:
      - dev

jobs:
  eab-job:
    name: EAB Job
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build eab-emacs image
        env:
          VER: 0.0.12
        run: |
          docker build -f dockerfiles/Dockerfile.eab-emacs -t harbor.homew.keenetic.pro/eab/eab-emacs:$VER .
